### ISSUE TITLE
Sudden disappearance of GO's?

### ISSUE THREAD

**Issue by aidinzolghadr** [prime31/RecyclerKit#4]
Hi,

Since I've added RecyclerKit to my game, sometimes objects that are spawned out of the pool, get disappeared. I tried very hard but can't trace the problem. Is this a known bug? How can I track it?

Thanks.

**Comment by prime31** [comment]
TrashMan doesn't even store a reference to an object once it is spawned. You have to despawn the object for TrashMan to again have a reference to the object. Check your despawn calls and use the debugger with breakpoint a on them to track your objects.

Mike


On Feb 1, 2015, at 4:32 AM, Aidin Zolghadr <notifications@github.com> wrote:

Hi,

Since I've added RecyclerKit to my game, sometimes objects that are spawned out of the pool, get disappeared. I tried very hard but can't trace the problem. Is this a known bug? How can I track it?

Thanks.

**Comment by aidinzolghadr** [comment]
I understand but by removing references of RecycleKit and patching a simple pool that I wrote quickly, that problem went away.

Re your suggestion on how to track the problem, my objects get destroyed/despawned when they collide with specific GO's, but they disappear into thin air when they are just moving without any collision, I suspect a loose coroutine call that is fired after sometime that object is spawned.

I tried to check your coroutines but could not find anything related to my suspicion.

I'm under a very tight deadline and cant' track the issue but if no one does, I'll go after it early next week.

Thanks.
