### ISSUE TITLE
ObjectComponent version returns null GameObjects when testing in the editor

### ISSUE THREAD

**Issue by iainlobb** [prime31/RecyclerKit#6]
I have no idea why, but in the editor, every few play-throughs spawn will return null instead of a GameObject. Deleting the bins from Trashman and recreating them fixes the problem, but it always returns a few plays later. Bit of a deal-breaker!

**Comment by prime31** [comment]
It is quite possible some bugs exist in the ObjectComponent version. It is
also very likely that it is it many commits behind the standard branch.
The ObjectComponent branch was just made to do some testing with a
different approach and it wasnt even battle tested.

That being said, if you fix any issue feel free to send over a pull
request. Otherwise, I would suggest using the standard branch which has
been used a lot in production.


Mike

**Comment by iainlobb** [comment]
No worries - I'm either going to try and fix it or build something similar from scratch - I haven't decided yet. The onSpawn / onDespawn events are really important to my game though - there would be quite a bit of manually calling init methods without them.

**Comment by prime31** [comment]
There is an event with the standard beach as well but it is a lot more general which isn't optimal in some cases.

Mike


On Feb 28, 2015, at 4:47 PM, Iain Lobb <notifications@github.com> wrote:

No worries - I'm either going to try and fix it or build something similar from scratch - I haven't decided yet. The onSpawn / onDespawn events are really important to my game though - there would be quite a bit of manually calling init methods without them.
